import SnapKit
import UIKit

final class EULAController: UIViewController {
  override func viewDidLoad() {
    super.viewDidLoad()
    modalPresentationStyle = .overFullScreen
    isModalInPresentation = true
    view.backgroundColor = UIColor.black.withAlphaComponent(0.6)

    let panel = UIView()
    panel.backgroundColor = .white
    panel.layer.cornerRadius = 24

    let title = UIFactory.label("EULA", size: 28, weight: .bold)
    title.textAlignment = .center

    let text = UITextView()
    text.isEditable = false
    text.isSelectable = false
    text.backgroundColor = .clear
    text.font = .systemFont(ofSize: 15)
    text.textColor = AppTheme.ink
    text.textContainerInset = UIEdgeInsets(top: 4, left: 0, bottom: 12, right: 0)
    text.text = """
      Welcome to Viraa! To create a positive, safe, and supportive space for our wild water community, the following content is strictly prohibited on the app:

      1. Any content involving child harm, pornography, and other materials detrimental to minors' physical and mental health, including but not limited to text, images, or audio.

      2. False and harmful public information, including false content generated by AI or other means that disrupts public order, especially fake safety or location guides regarding wild water activities.

      3. Violent content, cyberbullying, hazardous behavior promotion, and any content that promotes pornography, illegal acts, or disrupts the network ecological environment. Specifically, content inciting unequipped or unsafe wild water ventures is forbidden.

      4. If any of the above violations are detected, your uploaded posts, voice messages, comments, and other published content will be deleted, and your account may face restrictions or termination. By clicking the confirmation button, you agree to abide by the Terms of Use and Privacy Policy of Viraa.
      """

    let cancel = UIFactory.button(
      "Cancel", background: AppTheme.surface, foreground: AppTheme.ink)
    let agree = UIFactory.button("Agree", background: AppTheme.blue)
    cancel.addTarget(self, action: #selector(cancelTap), for: .touchUpInside)
    agree.addTarget(self, action: #selector(agreeTap), for: .touchUpInside)

    let row = UIStackView(arrangedSubviews: [cancel, agree])
    row.spacing = 8
    row.distribution = .fillEqually

    view.addSubview(panel)
    panel.addSubview(title)
    panel.addSubview(text)
    panel.addSubview(row)

    panel.snp.makeConstraints {
      $0.leading.trailing.bottom.equalToSuperview()
      $0.top.equalTo(view.safeAreaLayoutGuide).offset(40)
    }
    title.snp.makeConstraints {
      $0.top.equalToSuperview().offset(30)
      $0.leading.trailing.equalToSuperview().inset(20)
    }
    row.snp.makeConstraints {
      $0.leading.trailing.equalToSuperview().inset(20)
      $0.bottom.equalTo(view.safeAreaLayoutGuide).inset(16)
      $0.height.equalTo(52)
    }
    text.snp.makeConstraints {
      $0.top.equalTo(title.snp.bottom).offset(12)
      $0.leading.trailing.equalToSuperview().inset(20)
      $0.bottom.equalTo(row.snp.top).offset(-14)
    }
  }

  @objc private func cancelTap() { exit(0) }

  @objc private func agreeTap() {
    AppRepository.shared.acceptEULA()
    dismiss(animated: true)
  }
}
